name: Release SAMPLE
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Build Conty
      run: |
        rm -Rf utils_dwarfs.tar.gz
        wget -q https://github.com/ivan-hc/Conty/releases/download/utils/utils_dwarfs.tar.gz
        chmod +x create-arch-bootstrap.sh create-conty.sh
        sudo ./create-arch-bootstrap.sh && ./create-conty.sh
        
    - uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: continuous-SAMPLE
        github_token: ${{ secrets.GITHUB_TOKEN }}
        delete_release: true

    - uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: "continuous-SAMPLE"

    - uses: softprops/action-gh-release@v1
      with:
        files: ./conty.sh*
        prerelease: false
        draft: false
        tag_name: continuous-SAMPLE
        name: SAMPLE
